apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminPage
  labels:
    app: adminPage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminPage
  template:
    metadata:
      labels:
        app: adminPage
    spec:
      containers:
        - name: adminPage
          image: username/adminPage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5