apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapage
  labels:
    app: mapage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapage
  template:
    metadata:
      labels:
        app: mapage
    spec:
      containers:
        - name: mapage
          image: username/mapage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5